openapi: 3.0.1
info:
  title: API de Carritos
  description: API para la gestión de carritos de compra
  version: "1.0.0"
paths:
  /carts:
    get:
      summary: Obtener todos los carritos
      responses:
        '200':
          description: Lista de carritos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
    post:
      summary: Crear un nuevo carrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        '201':
          description: Carrito creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /carts/{cartId}:
    put:
      summary: Modificar un carrito existente
      parameters:
        - in: path
          name: cartId
          schema:
            type: string
          required: true
          description: ID del carrito a modificar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        '200':
          description: Carrito modificado exitosamente
        '404':
          description: Carrito no encontrado
    delete:
      summary: Eliminar un carrito existente
      parameters:
        - in: path
          name: cartId
          schema:
            type: string
          required: true
          description: ID del carrito a eliminar
      responses:
        '200':
          description: Carrito eliminado exitosamente
        '404':
          description: Carrito no encontrado
components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer