openapi: 3.0.1
info:
  title: API de Productos
  description: API para la gestión de productos
  version: "1.0.0"
paths:
  /products:
    get:
      summary: Obtener todos los productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Obtener un producto por ID
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: ID del producto
      responses:
        '200':
          description: Producto obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
    put:
      summary: Modificar un producto existente
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: ID del producto a modificar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto modificado exitosamente
        '404':
          description: Producto no encontrado
    delete:
      summary: Eliminar un producto existente
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: ID del producto a eliminar
      responses:
        '200':
          description: Producto eliminado exitosamente
        '404':
          description: Producto no encontrado
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        owner:
          type: string